name: push and Scheduled action

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Display Node.js version
      run: node --version

    - name: Display NPM version
      run: npm --version

    - name: List files in workspace
      run: ls -la

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  scheduled-task:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run custom script
      run: |
        echo "Running scheduled task"
        echo "Hora atual: $(date)"
        echo "Esse script é executado a cada hora"
